# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jindriska Deckerova | Personal webpage
email: jindriska.deckerova@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All projects, publications, and science fun facts at one place.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://deckejin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jindeckerova
github_username:  deckejin

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# Site Author
author:
  name             : "Jindřiška Deckerová"
  avatar           : "/images/photo.jpeg"
  bio              : "PhD student at the CTU in Prague. Focus on routing and multi-goal path planning."
  bio_long         : "I am 4th year PhD student at the Czech Technical University in Prague. I work in the Computational Robotics Laboratory with the Articial Inteligence Center in Faculty of Electrical Engineering. My main focus is on the routing problems, the optimal solution of these problems and solution in dynamic environments. Besides, one of my hobbies is popularization of science. 
  <br><br>I have a podcast with my friend Míša called <a href=\"https://open.spotify.com/show/0RALXyXqLX2lOWcEzm48EC?si=04c080b1e5fe4e1d\">věda bez cenzury</a> where we talk about doctorate studies, academia, and science. "
  university       : "Czech Technical University in Prague"
  location         : "Prague"
  googlescholar    : "https://scholar.google.com/citations?user=SCHOLAR_ID&user=RERahYwAAAAJ"
  email            : "jindriska.deckerova@gmail.com"
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "deckejin"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "deckejin-428898120"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "0000-0001-7182-8698"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "jindeckerova"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


collections:
  publications:
      output: true
  news:
      output: true
  education:
      output: true
  awards:
      output: true
  community:
      output: true
  media:
      output: true
  other:
      output: true
  skills:
      output: true
  teaching:
      output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - scripts
  - bibtex
  - run_locally.sh
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
